name: Cypress CI

on:
  schedule:
    - cron: '30 0 * * *' # Runs at 6 AM IST (UTC+5:30)
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Replace salesforcePassword in uat.json
        run: |
          jq '.env.salesforcePassword=env.LOCAL_SALESFORCE_PASSWORD' config/uat.json > tmp.json && mv tmp.json config/uat.json
        env:
          LOCAL_SALESFORCE_PASSWORD: ${{ secrets.LOCAL_SALESFORCE_PASSWORD }}

      - name: Run Cypress tests
        run: npx cypress run --headless --browser chrome
        continue-on-error: false

      - name: Upload Cypress screenshots (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload Cypress videos (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos